version: '2'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
     - 3306:3306
    volumes:
     - mysql_data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD= ##(Mysql 관리자 비밀번호, 관리자 계정은 root)
     - MYSQL_USER=KimGaNe ##(Mysql 사용자 계정)
     - MYSQL_PASSWORD=KimGaNe ##(Mysql 사용자 계정 비밀번호)
    user: 1000:100
